### ISSUE TITLE
Can't see any rss feeds after upgrading to 0.2

### ISSUE THREAD

**Issue by appetizermonster** [mistic100/hain-plugin-rss#1]
and I get this error from the console.

```
2016-05-01T15:36:28.140Z - debug: DEBUG: Parsed https://news.ycombinator.com/rss.
2016-05-01T15:36:28.144Z - debug: DEBUG: Fetched 1 feeds
2016-05-01T15:36:33.839Z - debug: TypeError: feed.maxDate.getTime is not a function
    at _.sortBy.feed (C:\Users\heejin\AppData\Local\hain-user\plugins\hain-plugin-rss\index.js:160:46)
    at C:\Users\heejin\AppData\Local\hain-user\plugins\hain-plugin-rss\node_modules\lodash\lodash.js:3335:18
    at arrayMap (C:\Users\heejin\AppData\Local\hain-user\plugins\hain-plugin-rss\node_modules\lodash\lodash.js:620:23)
    at C:\Users\heejin\AppData\Local\hain-user\plugins\hain-plugin-rss\node_modules\lodash\lodash.js:3334:24
    at C:\Users\heejin\AppData\Local\hain-user\plugins\hain-plugin-rss\node_modules\lodash\lodash.js:3151:27
    at C:\Users\heejin\AppData\Local\hain-user\plugins\hain-plugin-rss\node_modules\lodash\lodash.js:4308:15
    at baseMap (C:\Users\heejin\AppData\Local\hain-user\plugins\hain-plugin-rss\node_modules\lodash\lodash.js:3150:7)
    at baseOrderBy (C:\Users\heejin\AppData\Local\hain-user\plugins\hain-plugin-rss\node_modules\lodash\lodash.js:3333:2
0)
    at Function.<anonymous> (C:\Users\heejin\AppData\Local\hain-user\plugins\hain-plugin-rss\node_modules\lodash\lodash.
js:9013:14)
    at Function.sortBy (C:\Users\heejin\AppData\Local\hain-user\plugins\hain-plugin-rss\node_modules\lodash\lodash.js:98
73:31)
```

**Comment by mistic100** [comment]
Thank you :-)

For now you can change the feed order setting to name or unread
